views:
  - name: line_items_view

    cubes:
      - join_path: line_items
        includes:
          - created_at
          - count

      - join_path: line_items.products
        includes:
          - product_category

      - join_path: line_items.orders.users
        prefix: true
        includes: 
          - city
          - state
          